### ISSUE TITLE
Replace Provisioner by Kyma Infrastructure Manager [EPIC]

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/infrastructure-manager#112]
**Description**

The Provisioner has to be replaced by the Kyma Infrastrcuture Manager. The logic of the Provisioner has to be migrated into the Infrastructure Manager, but also considering already planned new features. This could required a rethinking of the current software architecture to ensure a flexible and extensible but also maintainable software structure of the Infrastructure Manager.

AC:
- [x] kyma-project/infrastructure-manager#134
  - [x] kyma-project/infrastructure-manager#125
    - [x] https://github.com/kyma-project/infrastructure-manager/pull/176
    - [x] Prepare CR examples for each plan we have 
  - [x] https://github.com/akgalwas/infrastructure-manager/pull/1
  - [x] [Finalise alignments under an open source ADR](https://github.com/kyma-project/infrastructure-manager/pull/202)
- [x] Main implementation part
  - [x] kyma-project/infrastructure-manager#197
    - [x] (optional?) consider extracting that to a separate module (ask @tobiscr about this one)
  - [x] kyma-project/infrastructure-manager#184
  - [x] kyma-project/infrastructure-manager#206
  - [x] kyma-project/infrastructure-manager#193
  - [x] kyma-projectinfrastructure-manager#185
  - [x] kyma-project/infrastructure-manager#250
  - [x] kyma-project/infrastructure-manager#270
  - [x] kyma-projectinfrastructure-manager#209
  - [x] kyma-project/infrastructure-manager#282
   - [x] kyma-projectinfrastructure-manager#198
  - [x] kyma-project/infrastructure-manager#232
  - [x] kyma-project/infrastructure-manager#264
  - [x] kyma-project/infrastructure-manager#230
  - [x] kyma-project/infrastructure-manager#286
  - [x] kyma-project/infrastructure-manager#284
  - [x] kyma-project/infrastructure-manager#299 
  - [x] kyma-project/infrastructure-manager#320
  - [x] kyma-project/infrastructure-manager#324
  - [x] kyma-project/infrastructure-manager#346
  - [x]  kyma-project/infrastructure-manager#343   
  - [x] Enable KIM on Dev and Stage in preview plan

- [x] Extended Provisioning functionalities (Prio I -required with go-live)
  - [x] Make sure that the new clusters shoot specs generated by KIM are the same as the ones created by Provisioner
   - [x] kyma-project/infrastructure-manager#103 
   - [x] https://github.com/kyma-project/infrastructure-manager/issues/381
   - [x] kyma-project/infrastructure-manager#14
   - [x] kyma-project/infrastructure-manager#113

- [x] Extended Provisioning functionalities (Prio II - required after go live)
  - [x] kyma-project/infrastructure-manager#241 
  - [x] kyma-project/infrastructure-manager#342
   - [x] kyma-project/infrastructure-manager#46 (Q1/25 -> **Deadline: end of FEB**)

- [x] Migration
    - [x] kyma-project/infrastructure-manager#187
    - [x] kyma-project/infrastructure-manager#183
    - [x] kyma-project/infrastructure-manager#242
    - [x] kyma-project/infrastructure-manager#186
    - [x] kyma-project/infrastructure-manager#207
    - [x] kyma-project/infrastructure-manager#335 
    - [x] Migrate STAGE
    - [x] https://github.com/kyma-project/infrastructure-manager/issues/251
    - [x] Migrate PROD
    
- [x] Stabilisation and Hardening (after MVP)
  - [x] make a semver release of kim and use that version in all landscapes
  - [x] Refactor Intialize state to make it smaller 
  - [x] kyma-project/infrastructure-manager#332
  - [x] kyma-project/infrastructure-manager#113
  - [x] #156 
  - [x] kyma-project/infrastructure-manager#208
  - [x] kyma-project/infrastructure-manager#192
  - [x] kyma-project/infrastructure-manager#244 
  - [x] Move [Runtime CR examples](https://github.com/kyma-project/infrastructure-manager/pull/345) to a place that would be a single source of truth for both KIM and KEB and would not need to be obfuscated (and therefore could be applied right away for testing purposes). 

- [x] Cleanup
  - [x] https://github.com/kyma-project/infrastructure-manager/issues/658

**Reasons**

Replacing the old Kyma Provisioner with the Kyma Infrastructure Manager to follow new KCP architectural paradigm (K8s native application).

**Attachments**

**Depends on**
https://github.com/kyma-project/infrastructure-manager/issues/134

**Comment by tobiscr** [comment]
Issue for @kyma-project/gopher  for enabling KIM in Dry-Run mode on KCP DEV + STAGE:
