### ISSUE TITLE
Implement migration script to generate Runtime CRs by using Shoot-Spec CRs from Gardener

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/infrastructure-manager#183]
**Reason**
We have to migrate existing clusters that are currently managed via Provisioner, to KIM.

**How**
When creating a new CR, we should treat the Gardener's shoot spec as the single source of truth (KEB's or Provisioner database might not have valid information)

**Acceptance Criteria**
- [x] CR should be enriched with the corresponding list of ClusterRoleBindings subjects' names 
- [x] CR should be enriched with [additional labels](https://github.com/kyma-project/infrastructure-manager/pull/202/files#diff-65d1bafd0a4f960db4f1f29c20490a4e8fb6edb1e086eb8025a98012965c79d7R58-R67) (e.g. from Kyma's resource) 
- [x] CR should be created only if it does not yet exist on the cluster
- [x] Migrator should accept list of clusters that should be migrated (see [this](https://github.com/kyma-project/infrastructure-manager/issues/183#issuecomment-2120295956))
  - [x] Figure out what to do with clusters that does not have `kcp.provisioner.kyma-project.io/runtime-id` label
- [x] Migrator should save Runtime CR on the specified location  (see [this](https://github.com/kyma-project/infrastructure-manager/issues/183#issuecomment-2120295956))
- [x] Migrator should send in stdout a meaningful output for each migrated CR  (see [this](https://github.com/kyma-project/infrastructure-manager/issues/183#issuecomment-2120295956))
- [x] ~(to be confirmed if needed) use the init containers approach~ - does not make sense in this case
- [x] update docs (readme)

**Dependencies**
- #197 (can be started, but not finalized before this)

**Comment by Disper** [comment]
Received some early feedback from @akgalwas  and @m00g3n on the script usage.

1. It would be great if the migrator would accept input that will contain the list to be migrated `shootNames`
- shootName1
- shootName2
2. As the first output (stdout), it should produce following
```
{
  shoot_name,
  status {OK/ERROR/ALREADY_EXIST},
  error_type,
  path_to_output_file    
}
```
3. As the second output, it should save on the specified location yamls which contain Runtime CRs, so they could be easily applied or investigated
