### ISSUE TITLE
Implement mutating webhook to inject node affinity for Kyma workload

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/infrastructure-manager#396]
**Description**

By introducing multiple worker pools, a mutating Webhook is required which ensures that workloads assigned to the namespace `kyma-system` are always use a node-selector which deploys them only on the Kyma worker pool (see #364 ).

The mutation webhook has to inject the `nodeSelector` field to all pods which are deployed into the `kyma-system` namespace.

To mitigate the risk of accidentally "killing" all pods by assigning an invalid node select, the Webhook has to check during its bootstrap the existence of the worker-pool name on all nodes. **If not at least one node exists which has the expected worker-node name, the admission-webhook has to print an error BUT not inject any node-selector to any pod.**

AC:
- [x] Certificates for the webhook can be generated with different approaches. Requirement is to rotate them regularly (max 90 day?). Investigate the different approaches in Kyma and decide which one we use for this webhook:
    * Create certificate in an init-container during bootstrap (like Otters are doing it)
    * Create certificate via crypto-library during bootstrap (like Goats are handling it, see [code](https://github.com/kyma-project/api-gateway/blob/main/controllers/certificate/certificate.go))
    * Use cert-manager for re-creating certificates (afaik Jellies are doing that)
    - [x] Implement the certificate generation and ensure the Webhook is using only valid and automatically rotate certificate
- [x] `nodeSelector` is injected by the webhook into all Kyma workloads (Pods, Jobs, StatefulSets) to ensure they run only on the Kyma worker pool (see #364  for more details)
- [x] Bundle the admission webhook as Kyma module to be deployed as mandatory module by KLM (like Warden, see https://github.tools.sap/kyma/module-manifests/tree/main/modules/warden) - @m00g3n 
    - [x] Depending on this decision, bundle the mutating webhook as Kyma module (either standalone module or combined module which includes also Warden). => **We agreed to have dedicated modules - no shared modules including content from different teams**
- [x] Cover following test cases in an E2E setup (using a real Kyma runtime): - @mvshao 
     - [x] Case 1: Kyma-Worker pool has expected name: 
         - [x] Deploy SNATCH manually in the SKR
         - [x] Create a second namespace 
         - [x] Ensure the Kyma namespace has the label `operator.kyma-project.io/managed-by: kyma`
         - [x] Deploy a pod to `kyma-system`namespace:  pods are receiving the `node-selector` and were scheduled (referring to worker-pool `cpu-worker-0`, see [comment below](https://github.com/kyma-project/infrastructure-manager/issues/396#issuecomment-2539402921)) + no annotation was set by Webhook on the pod.
         - [x] Deploy a pod to the second namespace: this pod should not receive any `node-selector` or annotation.
     - [x] Case 2: Kyma-Worker pool has different name: all new scheduled Kyma pods don't receive an `node-selector` + they get an annotation indicating that expected worker-pool is missing
         - [x] Deploy a pod to `kyma-system`namespace:  pods are NOT receiving the `node-selector` but an annotation was set by Webhook on the pod.
         - [x] Deploy a pod to the second namespace: this pod should not receive any `node-selector` or annotation.
     - [x] Case 3: Kyma Worker-Pool with wrong name gets "renamed" (<< recreated) and has finally the expected name: all  pods scheduled after the Webhook is alive, will receive the node-selector and be scheduled on the worker-pool
         - [x] Deploy a pod to `kyma-system`namespace:  pods are receiving the `node-selector` and were scheduled (referring to worker-pool `cpu-worker-0`, see [comment below](https://github.com/kyma-project/infrastructure-manager/issues/396#issuecomment-2539402921)) + no annotation was set by Webhook on the pod.
         - [x] Deploy a pod to the non-labeled namespace: this pod should not receive any `node-selector` or annotation.
- [x] We have to adjust the labeing the `kyma-system` namespace and add the label `operator.kyma-project.io/managed-by: kyma` -> tbc if we do it with KIM or with KLM - @m00g3n 
- [x] Risk mitigation
    - [x] before we rollout the module ,we run a short script to check if the expected worker-pool name is defined/exists in each cluster in all KCP landscapes - @mvshao @m00g3n 
    - [x] the webhook checks during its bootstrap the existence of at least one worker-node which includes the expected woker-pool name as label.
        - [x] If no node could be found, the webhook is not allowed to inject the `node-selector` to any pod
        - [x] An expressive error message is logged which indicates this mis-configuration
        - [x] [Monitoring is reporting the unavailability of the webhook caused by a misconfiguration ](https://github.com/kyma-project/kim-snatch/issues/40)
     - [x] Verify Security Scanners and fix security vulnerabilities
         - [x] Mend: https://pages.github.tools.sap/kyma/security-dashboard/#/mend?date=2025-01-08&teams=Framefrog&modules=snatch @mvshao 
         - [x] BDBA: https://pages.github.tools.sap/kyma/security-dashboard/#/blackduck-skr?date=2025-01-08&teams=Framefrog&modules=kim-snatch @tobiscr 
         - [x] Checkmarx: https://pages.github.tools.sap/kyma/security-dashboard/#/checkmarx-modular?date=2025-01-08&teams=Framefrog&modules=kim-snatch @tobiscr 
- [x] Migration script has to be implemented which handles 
    - [x] ~All existing `kyma-system` namespaces receive the label `operator.kyma-project.io/managed-by: kyma`~ - @VOID404 
    - [x] ~All deployed pod in `kyma-system` namespaces are patched with the `node-selector` field to ensure they will be scheduled on the Kyma workerpool.~ -> obsolete, all pods will be anyway restarted latest when the cluster upgrade happens. No dedicated migration planned by Framefrogs.
         - [x] We have to test if a pod gets rescheduled when it's deployed and we are adding the `node-selector` by patching the pod manifest - @VOID404 
    - [x] Rollout strategy
        - [x] Prepare latest webhook-image
        - [x] Deploy webhook to KCP DEV manually
        - [x] Wait for testing-confirmation from @kyma-project/goat 
        - [x] After retrieving compatibility-confirmation from @kyma-project/goat , we deploy webhook to experimental channel (will trigger the rollout to DEV/STAGE via Argo-CD)

**Reasons**

Ensure that Kyma workloads are only running on the Kyma worker pool.

**Attachments**

**Comment by tobiscr** [comment]
See https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/

**Comment by tobiscr** [comment]
this is the current node-selector for the Kyma workerpool:

```
spec:
   nodeSelector:
     worker.gardener.cloud/pool: "cpu-worker-0"
```
